---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: check-json
- repo: https://github.com/markdownlint/markdownlint
  rev: e31711c0db57df9b350fbaeaae6de745972f3e66
  hooks:
  - id: markdownlint_docker
    name: Markdown linting
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.3
  hooks:
  - id: yamllint
    args: [--format, parsable, --strict]
